sensor:
  - platform: dewpoint
    sensors:
      dewpoint_outside:
        temperature: sensor.aquara_outside_temperature
        rel_hum: sensor.aquara_outside_humidity
  - platform: template
    sensors:
      rain_today:
        unit_of_measurement: 'in'
        value_template: "{{ (states.sensor.current_daily_rain.state | float / 100) | round(2) }}"
      rain_rate_in:
        unit_of_measurement: 'in/hr'
        value_template: "{{ (states.sensor.rain_rate.state | float / 100) | round(2) }}"
      pws_url:
        value_template: !secret pws_url
      press_in:
        unit_of_measurement: in
        value_template: "{{ (states.sensor.aquara_outside_pressure.state | float * 0.02953) | round(2) }}"

rest_command:
  update_wunderground:
    url: "{{ states.sensor.pws_url.state }}tempf={{ states.sensor.aquara_outside_temperature.state }}&humidity={{ states.sensor.aquara_outside_humidity.state }}&dewptf={{ states.sensor.dewpoint_outside.state }}&baromin={{ states.sensor.press_in.state }}&rainin={{ states.sensor.rain_rate_in.state }}&dailyrainin={{ states.sensor.rain_today.state }}"
