- alias: Left Office Blind Send Value on Boot
  trigger:
  - platform: mqtt
    topic: habc/office_l/tele/state
    # Optional
    payload: BOOT
  action:
  - data:
      payload_template: "{{ states.sensor.left_office_blind_position.state }}"
      topic: habc/office_l/command/set/current
    service: mqtt.publish
- alias: Center Office Blind Send Value on Boot
  trigger:
  - platform: mqtt
    topic: habc/office_c/tele/state
    # Optional
    payload: BOOT
  action:
  - data:
      payload_template: "{{ states.sensor.center_office_blind_position.state }}"
      topic: habc/office_c/command/set/current
    service: mqtt.publish
- alias: Right Office Blind Send Value on Boot
  trigger:
  - platform: mqtt
    topic: habc/office_r/tele/state
    # Optional
    payload: BOOT
  action:
  - data:
      payload_template: "{{ states.sensor.right_office_blind_position.state }}"
      topic: habc/office_r/command/set/current
    service: mqtt.publish
