- alias: Close Blinds When Away or Going to Bed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: arming
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: arming
      to: armed_away
  action:
    - service: mqtt.publish
      data:
        payload: CLOSE
        topic: habc/all/command/set/state
    - delay: '00:00:30'
    - service: input_boolean.turn_off
      entity_id: input_boolean.blinds_manual

- alias: 'Close blind at dusk'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -2.5
  action:
    - service: cover.close_cover
      entity_id: cover.house_blinds
    - delay: '00:00:30'
    - service: input_boolean.turn_off
      entity_id: input_boolean.blinds_manual

- alias: Open Blinds When Awake and Sun Up
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: armed_home
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 0
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 0
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.blinds_manual
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.area_001
          state:  disarmed
        - condition: state
          entity_id: alarm_control_panel.area_001
          state:  armed_home
  action:
    - service: mqtt.publish
      data:
        payload: OPEN
        topic: habc/all/command/set/state

- alias: All Windows Same Position
  trigger:
    - platform: state
      entity_id: cover.office_blinds
  condition:
    - condition: template
      value_template: '{{ states.cover.center_office_blind.attributes.current_position | int == states.cover.right_office_blind.attributes.current_position | int == states.cover.left_office_blind.attributes.current_position | int == states.cover.guest_blind.attributes.current_position | int == states.cover.server_room_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states.cover.center_office_blind.attributes.current_position }}'
        topic: habc/all/tele/currentpct
        retain: 'true'

- alias: All Windows Various Positions
  trigger:
    - platform: state
      entity_id: cover.office_blinds
  condition:
    - condition: template
      value_template: '{{not states.cover.center_office_blind.attributes.current_position | int == states.cover.right_office_blind.attributes.current_position | int == states.cover.left_office_blind.attributes.current_position | int == states.cover.guest_blind.attributes.current_position | int == states.cover.server_room_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/all/tele/currentpct
        retain: 'true'

- alias: Open House Blinds
  trigger:
    - platform: state
      entity_id: switch.house_blinds
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.house_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.house_blinds
      

- alias: Close House Blinds
  trigger:
    - platform: state
      entity_id: switch.house_blinds
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.house_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.house_blinds

- alias: House Blinds Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.house_blinds
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.house_blinds
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.house_blinds

- alias: House Blinds Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.house_blinds
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.house_blinds
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.house_blinds

- alias: Alexa Open House Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.house_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.house_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.house_blinds_open

- alias: Alexa Close House Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.house_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.house_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.house_blinds_close

- alias: Blinds Moved Manually
  trigger:
    - platform: state
      entity_id: 
        - cover.left_office_blind
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.guest_blind
        - cover.server_room_blind
        - cover.left_den_blind
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_kitchen_blind
        - cover.right_kitchen_blind
        - cover.east_kitchen_blind
        - cover.left_shack_blind
        - cover.center_shack_blind
        - cover.right_shack_blind
        - cover.left_master_blind
        - cover.center_master_blind
        - cover.right_master_blind
        - cover.west_master_blind
      to: 'closed'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.blinds_manual