- alias: Open Den Blinds
  trigger:
    - platform: state
      entity_id: switch.den_blinds_keypad
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.den_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.den_blinds

- alias: Close Den Blinds
  trigger:
    - platform: state
      entity_id: switch.den_blinds_keypad
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.den_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.den_blinds

- alias: Den Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.den_blinds
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.den_blinds_keypad
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_blinds_keypad
    

- alias: Den Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.den_blinds
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.den_blinds_keypad
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_blinds_keypad

- alias: Alexa Open Den Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.den_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.den_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.den_blinds_open

- alias: Alexa Close Den Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.den_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.den_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.den_blinds_close

- alias: Den Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
  condition:
    - condition: template
      value_template: '{{ states.cover.center_den_blind.attributes.current_position | int == states.cover.right_den_blind.attributes.current_position | int == states.cover.left_den_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states.cover.center_den_blind.attributes.current_position }}'
        topic: habc/den/tele/currentpct
        retain: 'true'

- alias: Den Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
  condition:
    - condition: template
      value_template: '{{not states.cover.center_den_blind.attributes.current_position | int == states.cover.right_den_blind.attributes.current_position | int == states.cover.left_den_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/den/tele/currentpct
        retain: 'true'