- alias: Open Guest Blinds
  trigger:
    - platform: state
      entity_id: switch.guest_blinds_keypad
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.guest_blind
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.guest_blind

- alias: Close Guest Blinds
  trigger:
    - platform: state
      entity_id: switch.guest_blinds_keypad
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.guest_blind
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.guest_blind

- alias: Guest Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.guest_blind
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.guest_blinds_keypad
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.guest_blinds_keypad

- alias: Guest Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.guest_blind
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.guest_blinds_keypad
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.guest_blinds_keypad

- alias: Alexa Open Guest Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.guest_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.guest_blind
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_blinds_open

- alias: Alexa Close Guest Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.guest_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.guest_blind
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_blinds_close