- alias: Open Kitchen Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.kitchen_blinds_keypad
        - switch.dining_room_blinds_keypad
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_blinds

- alias: Close Kitchen Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.kitchen_blinds_keypad
        - switch.dining_room_blinds_keypad
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_blinds

- alias: Kitchen Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      to: 'open'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: 
          - switch.kitchen_blinds_keypad
          - switch.dining_room_blinds_keypad
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_blinds_keypad
        - switch.dining_room_blinds_keypad
    

- alias: Kitchen Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      to: 'closed'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: 
          - switch.kitchen_blinds_keypad
          - switch.dining_room_blinds_keypad
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_blinds_keypad
        - switch.dining_room_blinds_keypad

- alias: Alexa Open Kitchen Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_blinds_open

- alias: Alexa Close Kitchen Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_blinds_close

- alias: Kitchen Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
  condition:
    - condition: template
      value_template: '{{ states.cover.east_kitchen_blind.attributes.current_position | int == states.cover.right_kitchen_blind.attributes.current_position | int == states.cover.left_kitchen_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states.cover.east_kitchen_blind.attributes.current_position }}'
        topic: habc/kitchen/tele/currentpct
        retain: 'true'

- alias: Kitchen Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
  condition:
    - condition: template
      value_template: '{{not states.cover.east_kitchen_blind.attributes.current_position | int == states.cover.right_kitchen_blind.attributes.current_position | int == states.cover.left_kitchen_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/kitchen/tele/currentpct
        retain: 'true'