- alias: Open Office Blinds
  trigger:
    - platform: state
      entity_id: switch.office_blinds
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.office_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.office_blinds

- alias: Close Office Blinds
  trigger:
    - platform: state
      entity_id: switch.office_blinds
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.office_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.office_blinds

- alias: Office Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.office_blinds
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.office_blinds
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.office_blinds
    

- alias: Office Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.office_blinds
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.office_blinds
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.office_blinds

- alias: Alexa Open Office Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.office_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.office_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.office_blinds_open

- alias: Alexa Close Office Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.office_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.office_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.office_blinds_close

- alias: Office Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
  condition:
    - condition: template
      value_template: '{{ states.cover.center_office_blind.attributes.current_position | int == states.cover.right_office_blind.attributes.current_position | int == states.cover.left_office_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states.cover.center_office_blind.attributes.current_position }}'
        topic: habc/office/tele/currentpct
        retain: 'true'

- alias: Office Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
  condition:
    - condition: template
      value_template: '{{not states.cover.center_office_blind.attributes.current_position | int == states.cover.right_office_blind.attributes.current_position | int == states.cover.left_office_blind.attributes.current_position }}'
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/office/tele/currentpct
        retain: 'true'