- alias: Open Server Blinds
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.server_room_blind

- alias: Close Server Blinds
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.server_room_blind

- alias: Server Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.server_blinds
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.server_blinds

- alias: Server Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.server_blinds
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.server_blinds

- alias: Alexa Open Server Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.server_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.server_room_blind
    - service: input_boolean.turn_off
      entity_id: input_boolean.server_blinds_open

- alias: Alexa Close Server Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.server_blinds_close
      to: 'on'
  action:
  - service: cover.close_cover
    entity_id: cover.server_room_blind
  - service: input_boolean.turn_off
    entity_id: input_boolean.server_blinds_close