- alias: Open Server Blinds
  trigger:
  - entity_id: switch.server_blinds
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.server_blind
    state: 'closed'
  action:
  - data:
      entity_id: cover.server_blind
    service: cover.open_cover

- alias: Close Server Blinds
  trigger:
  - entity_id: switch.server_blinds
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: cover.server_blind
    state: 'open'
  action:
  - data:
      entity_id: cover.server_blind
    service: cover.close_cover

- alias: Server Blind Keypad on if any Open
  trigger:
  - entity_id: cover.server_blind
    platform: state
    to: 'open'
  condition:
  - condition: state
    entity_id: switch.server_blinds
    state: 'off'
  action:
  - data:
      entity_id: switch.server_blinds
    service: switch.turn_on

- alias: Server Blind Keypad off if all Closed
  trigger:
  - entity_id: cover.server_blind
    platform: state
    to: 'closed'
  condition:
  - condition: state
    entity_id: switch.server_blinds
    state: 'on'
  action:
  - data:
      entity_id: switch.server_blinds
    service: switch.turn_off

- alias: Alexa Open Server Blinds
  trigger:
  - entity_id: input_boolean.server_blinds_open
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: cover.server_blind
    service: cover.open_cover
  - data:
      entity_id: input_boolean.server_blinds_open
    service: input_boolean.turn_off

- alias: Alexa Close Server Blinds
  trigger:
  - entity_id: input_boolean.server_blinds_close
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: cover.server_blind
    service: cover.close_cover
  - data:
      entity_id: input_boolean.server_blinds_close
    service: input_boolean.turn_off