title: The Geek House

resources: !include /config/lovelace/resources/resources.yaml

#################################################################
#                                                               #
#                    Compact Header Config                      #
#                                                               #
################################################################# 

cch:
  main_config: true
  background: 'rgba(150, 150, 150, 0.2)'
  #background: transparent
  menu: show
  options: show
  voice: show
  options: clock
  clock_format: '24'
  clock_date: true
  date_locale: en-us
  disable: false
  hide_tabs: 8
  default_tab: 0
  exceptions:
    - conditions:
        user_agent: fully-kitchen
      config:
        hide_tabs: 0 to 7
        default_tab: 8

#############################################################################################################################################
#                                                                                                                                           # 
#                                                                BEGIN VIEWS                                                                #
#                                                                                                                                           #
#############################################################################################################################################  
 
background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views: 

  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/rooms.yaml  
  - !include /config/lovelace/views/hvac.yaml
  - !include /config/lovelace/views/laundry.yaml
  - !include /config/lovelace/views/blinds.yaml
  - !include /config/lovelace/views/media.yaml
  - !include /config/lovelace/views/irrigation.yaml
  - !include /config/lovelace/views/system.yaml        
  - !include /config/lovelace/views/panels/kitchen.yaml
