cover:
  - platform: mqtt
    name: "Shack Blinds"
    command_topic: "habc/shack/command/set/state"
    set_position_topic: "habc/shack/command/set/positionpct"
    position_topic: "habc/shack/tele/currentpct"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0

input_boolean:

  shack_blinds_open:
    name: Cover Shack Open
    initial: off
    icon: mdi:blinds

  shack_blinds_close:
    name: Cover Shack Close
    initial: off
    icon: mdi:blinds

sensor:
  platform: average
  name: Shack Blinds Average Light Level
  entities:
    - sensor.left_shack_blind_light_level
    - sensor.center_shack_blind_light_level
    - sensor.right_shack_blind_light_level