cover:
  #House Blinds
  - platform: mqtt
    name: "House Blinds"
    command_topic: "habc/all/command/set/state"
    set_position_topic: "habc/all/command/set/positionpct"
    position_topic: "habc/all/tele/currentpct"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0

  #Office Blinds
  - platform: mqtt
    name: "Office Blinds"
    command_topic: "habc/office/command/set/state"
    set_position_topic: "habc/office/command/set/positionpct"
    position_topic: "habc/office/tele/currentpct"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0

  #Center Office Blind
  - platform: mqtt
    name: "Center Office Blind"
    command_topic: "habc/office_c/command/set/state"
    set_position_topic: "habc/office_c/command/set/positionpct"
    position_topic: "habc/office_c/tele/currentpct"
    availability_topic: "habc/office_c/tele/LWT"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

  #Right Office Blind
  - platform: mqtt
    name: "Right Office Blind"
    command_topic: "habc/office_r/command/set/state"
    set_position_topic: "habc/office_r/command/set/positionpct"
    position_topic: "habc/office_r/tele/currentpct"
    availability_topic: "habc/office_r/tele/LWT"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

  #Left Office Blind
  - platform: mqtt
    name: "Left Office Blind"
    command_topic: "habc/office_l/command/set/state"
    set_position_topic: "habc/office_l/command/set/positionpct"
    position_topic: "habc/office_l/tele/currentpct"
    availability_topic: "habc/office_l/tele/LWT"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

#Guest Room Blind
  - platform: mqtt
    name: "Guest Blind"
    command_topic: "habc/guest/command/set/state"
    set_position_topic: "habc/guest/command/set/positionpct"
    position_topic: "habc/guest/tele/currentpct"
    availability_topic: "habc/guest/tele/LWT"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

#Server Room Blind
  - platform: mqtt
    name: "Server Room Blind"
    command_topic: "habc/server/command/set/state"
    set_position_topic: "habc/server/command/set/positionpct"
    position_topic: "habc/server/tele/currentpct"
    availability_topic: "habc/server/tele/LWT"
    #retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

input_boolean:

  office_blinds_open:
    name: Blinds Office Open
    initial: off
    icon: mdi:blinds

  office_blinds_close:
    name: Blinds Office Close
    initial: off
    icon: mdi:blinds

  guest_blinds_open:
    name: Blinds Guest Open
    initial: off
    icon: mdi:blinds

  guest_blinds_close:
    name: Blinds Guest Close
    initial: off
    icon: mdi:blinds

  server_blinds_open:
    name: Blinds Server Open
    initial: off
    icon: mdi:blinds

  server_blinds_close:
    name: Blinds Server Close
    initial: off
    icon: mdi:blinds

  house_blinds_open:
    name: Blinds House Open
    initial: off
    icon: mdi:blinds

  house_blinds_close:
    name: Blinds House Close
    initial: off
    icon: mdi:blinds

sensor:
  #Driver Status Messages

  - platform: mqtt
    name: "Left Office Blind Version"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Left Office Blind Uptime"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Left Office Blind RSSI"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Left Office Blind IP"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Left Office Blind Free Heap"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Left Office Blind Heap Fragmentation"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Left Office Blind Core Version"
    state_topic: "habc/office_l/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Version"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Center Office Blind Uptime"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind RSSI"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind IP"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Free Heap"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Center Office Blind Heap Fragmentation"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Core Version"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Right Office Blind Version"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Right Office Blind Uptime"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Right Office Blind RSSI"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Right Office Blind IP"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Right Office Blind Free Heap"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Right Office Blind Heap Fragmentation"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Right Office Blind Core Version"
    state_topic: "habc/office_r/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/office_r/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Guest Blind Version"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Guest Blind Uptime"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Guest Blind RSSI"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Guest Blind IP"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Guest Blind Free Heap"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Guest Blind Heap Fragmentation"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Guest Blind Core Version"
    state_topic: "habc/guest/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/guest/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Server Room Blind Version"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Server Room Blind Uptime"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Server Room Blind RSSI"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Server Room Blind IP"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Server Room Blind Free Heap"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Server Room Blind Heap Fragmentation"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Server Room Blind Core Version"
    state_topic: "habc/server/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/server/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"