light:
  - platform: mqtt
    name: "Kitchen LED 6 RGB"
    state_topic: "h801/kitchen_6/tele/current"
    command_topic: "h801/kitchen_6/command/set/rgb/power"
    brightness_state_topic: "h801/kitchen_6/tele/current"
    brightness_command_topic: "h801/kitchen_6/command/set/rgb/brightness"
    rgb_state_topic: "h801/kitchen_6/tele/current"
    rgb_command_topic: "h801/kitchen_6/command/set/rgb/color"
    state_value_template: "{{value_json['rgb_power']}}"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
  - platform: mqtt
    name: "Kitchen LED 6 W2"
    state_topic: "h801/kitchen_6/tele/current"
    command_topic: "h801/kitchen_6/command/set/w2/power"
    brightness_state_topic: "h801/kitchen_6/tele/current"
    brightness_command_topic: "h801/kitchen_6/command/set/w2/brightness"
    state_value_template: "{{value_json['w2_power']}}"
    brightness_value_template: "{{value_json['w2_brightness']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
sensor:
  #Driver Status Messages
  - platform: mqtt
    name: "Kitchen LED 6 Status"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['status']}}"
  - platform: mqtt
    name: "Kitchen LED 6 Version"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['espVersion']}}"
  - platform: mqtt
    name: "Kitchen LED 6 Uptime"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['espUptime']}}"
  - platform: mqtt
    name: "Kitchen LED 6 RSSI"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['signalStrength']}}"
  - platform: mqtt
    name: "Kitchen LED 6 IP"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
  - platform: mqtt
    name: "Kitchen LED 6 Free Heap"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Kitchen LED 6 Heap Fragmentation"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
  - platform: mqtt
    name: "Kitchen LED 6 Core Version"
    state_topic: "h801/kitchen_6/tele/status"
    value_template: "{{value_json['espCore']}}" 
