sensor:
  - platform: integration
    source: sensor.eagle_current_power
    name: energy_used
    unit_prefix: k
    round: 2
utility_meter:
  energy_daily:
    source: sensor.energy_used
    cycle: daily
  energy_monthly:
    source: sensor.energy_used
    cycle: monthly
  energy_yearly:
    source: sensor.energy_used
    cycle: yearly