- alias: Garage Light Auto On
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.zone_002', 'physical_status', 'open') }}"
    - platform: state
      entity_id: sensor.zone_032
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.zone_031
      from: Normal
      to: Violated
  condition:
    - condition: state
      entity_id: switch.garage_light
      state: 'off'    
  action:
    - service: switch.turn_on
      entity_id: switch.garage_lights
    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Timer Reset
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.zone_002', 'physical_status', 'open') }}"
    - platform: state
      entity_id: sensor.zone_032
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.zone_031
      from: Normal
      to: Violated
  condition:
    - condition: state
      entity_id: switch.garage_lights
      state: 'on'    
  action:
    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Auto Off
  trigger:
    - event_data:
        entity_id: timer.garage_light
      event_type: timer.finished
      platform: event  
  action:
    - service: switch.turn_off
      entity_id: switch.garage_lights

- alias: Auto Attic Light
  trigger:
    - entity_id: sensor.zone_030
      platform: state
      to: Violated
    - entity_id: sensor.zone_030
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('light.attic_lights') == "off" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.attic_light
      
- alias: Auto Guest Closet Light
  trigger:
    - entity_id: sensor.zone_071
      platform: state
      to: Violated
    - entity_id: sensor.zone_071
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('light.guest_closet_light') == "off" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.guest_closet_light

- alias: Auto Pantry Light
  trigger:
    - entity_id: sensor.zone_048
      platform: state
      to: Violated
    - entity_id: sensor.zone_048
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('light.pantry_light') == "off" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.pantry_light

- alias: Auto Server Closet Light
  trigger:
    - entity_id: sensor.zone_072
      platform: state
      to: Violated
    - entity_id: sensor.zone_072
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('light.server_closet_light') == "off" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.server_closet_light

- alias: Auto Shed Light
  trigger:
    - entity_id: sensor.zone_049
      platform: state
      to: Violated
    - entity_id: sensor.zone_049
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('switch.shed_inside_light') == "off" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.shed_inside_light      
    
- alias: Master Closet Light Auto On
  trigger:
    - entity_id: sensor.zone_029
      platform: state
      to: Violated
  action:
    - service: switch.turn_on
      entity_id: switch.master_closet_light

- alias: Master Closet Light Auto Off
  trigger:
    - entity_id: sensor.zone_029
      platform: state
      to: Normal
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      entity_id: switch.master_closet_light    

- alias: Utility Room Light Auto On
  trigger:
    - entity_id: sensor.zone_026
      platform: state
      to: Violated
  action:
    - service: light.turn_on
      entity_id: light.utility_room_light

- alias: Uitlity Room Light Auto Off
  trigger:
    - entity_id: sensor.zone_026
      platform: state
      to: Normal
      for:
        minutes: 1
  action:
    - service: light.turn_off
      entity_id: light.utility_room_light