- alias: Garage Light Auto On
  trigger:

  - platform: template
    value_template: "{{ states.sensor.zone_002.attributes.physical status | string == 'open' }}"

  - platform: state
    entity_id: sensor.zone_032
    from: Normal
    to: Violated

  - platform: state
    entity_id: sensor.zone_031
    from: Normal
    to: Violated

  condition:
  - condition: state
    entity_id: switch.garage_lighting
    state: 'off'
    
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.garage_lighting

    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Timer Reset
  trigger:

  - platform: template
    value_template: "{{ states.sensor.zone_002.attributes.physical status | string == 'open' }}"

  - platform: state
    entity_id: sensor.zone_032
    from: Normal
    to: Violated

  - platform: state
    entity_id: sensor.zone_031
    from: Normal
    to: Violated

  condition:
  - condition: state
    entity_id: switch.garage_lighting
    state: 'on'
    
  action:
    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Auto Off
  trigger:
  - event_data:
      entity_id: timer.garage_light
    event_type: timer.finished
    platform: event
  
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.garage_lighting
    