- alias: Alexa Good Night Armed Night
  trigger:
    platform: state
    entity_id: input_boolean.goodnight_trigger
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_night
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: arming
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bedroom_lamps
    - service: light.turn_off
      data: 
        entity_id: light.master_suite_leds_rgb
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.goodnight_trigger
- alias: Alexa Good Night Not Armed Night
  trigger:
    platform: state
    entity_id: input_boolean.goodnight_trigger
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: disarmed
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bedroom_lamps
    - service: light.turn_off
      data: 
        entity_id: light.master_suite_leds_rgb
    - service: switch.turn_on
      data:
        entity_id: switch.output_178
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.goodnight_trigger
- alias: Alexa Bedtime
  trigger:
    platform: state
    entity_id: input_boolean.bedtime_trigger
    to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.output_178
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bedtime_trigger