- alias: House Armed and Secure
  trigger:
  - entity_id: alarm_control_panel.area_001
    from: arming
    platform: state
    to: armed_away
  condition:
  - condition: state
    entity_id: lock.front_door
    state: locked
  - condition: state
    entity_id: lock.back_door
    state: locked
  - condition: state
    entity_id: lock.garage_entry
    state: locked
  action:
  - service: notify.browser
    data:
      message: The alarm is fully armed in away mode and all doors are secure.
      title: House Secure
    
- alias: Master Going To Bed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: disarmed
    to: armed_night
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_home
    to: armed_night
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.master_bedroom_fan_1
  - service: light.turn_off
    data:
      entity_id: light.master_bedroom_light
  - service: switch.turn_on
    data:
      entity_id: switch.nuvo_zone_4_power
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/src
      payload: 4,6
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/vol
      payload: 4,40
  - service: switch.turn_off
    data:
      entity_id: switch.nuvo_zone_5_power

- alias: Update Wunderground
  trigger:
  - platform: time_pattern
    minutes: "*"
  action:
  - service: rest_command.update_wunderground

#When Hass Reboots
- alias: Initialize ISY Variables
  trigger:
    - platform: homeassistant
      event: start
  action:
  - delay:
      minutes: 5
  - service: rest_command.initialize_isy