- alias: Doorbell Alert
  trigger:
  - entity_id: switch.doorbell_pressed
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.fpp_status
    state: idle
  action:
  - data:
      payload: Doorbell
      topic: ElkSpeak/falcon/player/ElkSpeak/playlist/name/set
    service: mqtt.publish
  - data:
      entity_id: switch.doorbell_pressed
    service: switch.turn_off
- alias: Timer Alert
  trigger:
  - event_data:
      action: echotimer
    event_type: ifttt_webhook_received
    platform: event
  condition:
  - condition: state
    entity_id: sensor.fpp_status
    state: idle
  action:
  - data:
      payload: TimerEnd
      topic: ElkSpeak/falcon/player/ElkSpeak/playlist/name/set
    service: mqtt.publish
  - data:
      entity_id: switch.alexa_timer_end
    service: switch.turn_off
- alias: House Armed and Secure
  trigger:
  - entity_id: alarm_control_panel.area_001
    from: arming
    platform: state
    to: armed_away
  condition:
  - condition: state
    entity_id: lock.front_door
    state: locked
  - condition: state
    entity_id: lock.back_door
    state: locked
  - condition: state
    entity_id: lock.garage_entry
    state: locked
  action:
  - data:
      message: The alarm is fully armed in away mode and all doors are secure.
      title: House Secure
    service: notify.elk_pushover


- alias: Auto Guest Mode On
  trigger:
  - entity_id: device_tracker.karen
    platform: state
    to: home
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.guest_mode_led
- alias: Auto Guest Mode Off
  trigger:
  - entity_id: device_tracker.karen
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: switch.guest_mode_led
    state: 'on'
  action:
  - data:
      entity_id: switch.guest_mode_led
    service: switch.turn_off