- id: '1555552521835'
  alias: Doorbell Alert
  trigger:
  - entity_id: switch.doorbell_pressed
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.fpp_status
    state: idle
  action:
  - data:
      payload: Doorbell
      topic: ElkSpeak/falcon/player/ElkSpeak/playlist/name/set
    service: mqtt.publish
  - data:
      entity_id: switch.doorbell_pressed
    service: switch.turn_off
- id: '1555552705124'
  alias: Timer Alert
  trigger:
  - event_data:
      action: echotimer
    event_type: ifttt_webhook_received
    platform: event
  condition:
  - condition: state
    entity_id: sensor.fpp_status
    state: idle
  action:
  - data:
      payload: TimerEnd
      topic: ElkSpeak/falcon/player/ElkSpeak/playlist/name/set
    service: mqtt.publish
  - data:
      entity_id: switch.alexa_timer_end
    service: switch.turn_off
- id: '1555989598929'
  alias: House Armed and Secure
  trigger:
  - entity_id: alarm_control_panel.area_001
    from: arming
    platform: state
    to: armed_away
  condition:
  - condition: state
    entity_id: lock.front_door
    state: locked
  - condition: state
    entity_id: lock.back_door
    state: locked
  - condition: state
    entity_id: lock.garage_entry
    state: locked
  action:
  - data:
      message: The alarm is fully armed in away mode and all doors are secure.
      title: House Secure
    service: notify.elk_pushover
- id: '1556060938584'
  alias: Entry Light On
  trigger:
  - entity_id: switch.entry_lamp
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      brightness: 95
      entity_id: light.entry_lamp
    service: light.turn_on
- id: '1556060938585'
  alias: Entry Light Off
  trigger:
  - entity_id: switch.entry_lamp
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.entry_lamp
    service: light.turn_off
- id: '1556580060976'
  alias: Auto Guest Mode On
  trigger:
  - entity_id: device_tracker.karen
    platform: state
    to: home
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.guest_mode_led
- id: '1556580060998'
  alias: Auto Guest Mode Off
  trigger:
  - entity_id: device_tracker.karen
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: switch.guest_mode_led
    state: 'on'
  action:
  - data:
      entity_id: switch.guest_mode_led
    service: switch.turn_off
- alias: Master Bedroom LEDs On
  trigger:
  - entity_id: switch.master_leds_power
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom_leds_rgb
    service: light.turn_on
- alias: Master Bedroom LEDs Off
  trigger:
  - entity_id: switch.master_leds_power
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom_leds_rgb
    service: light.turn_off
- alias: Master Bathroom LEDs On
  trigger:
  - entity_id: switch.master_bathroom_leds_power
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.master_bathroom_led_rgb
    service: light.turn_on
- alias: Master Bedroom LEDs Off
  trigger:
  - entity_id: switch.master_bathroom_leds_power
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.master_bathroom_led_rgb
    service: light.turn_off