- alias: Entry Lamp On from Keypad
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.entry_light_a
      control: DON
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.entry_lamp
      brightness: 128
- alias: Entry Lamp Off from Keypad
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.entry_light_a
      control: DOF
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.entry_lamp
- alias: Entry Lamp Keypad On
  trigger:
  - entity_id: light.entry_lamp
    platform: state
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.entry_lamp
- alias: Entry Lamp Keypad Off
  trigger:
  - entity_id: light.entry_lamp
    platform: state
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.entry_lamp