- alias: Turn On Fireplace
  trigger:
    - platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.den_light_d
        control: DON
  condition:
    - condition: state
      entity_id: switch.fireplace
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.fireplace

- alias: Turn Off Fireplace
  trigger:
    - platform: event
      event_type: isy994_control
      event_data:
        entity_id: switch.den_light_d
        control: DOF
  condition:
    - condition: state
      entity_id: switch.fireplace
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.fireplace

- alias: Fireplace Keypad On if Fire On
  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.den_fireplace
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_fireplace

- alias: Fireplace Keypad Off if Fire Off
  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.den_fireplace
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_fireplace

- alias: Keep Fireplace Off When Away
  trigger:
    - platform: state
      entity_id: switch.fireplace
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: armed_away
  action:
    - service: switch.turn_off
      entity_id: switch.fireplace