- alias: Auto Guest Mode On
  trigger:
    - platform: state
      entity_id: device_tracker.karen
      to: home
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_mode
    - service: switch.turn_on
      entity_id: switch.guest_mode_led

- alias: Auto Guest Mode Off
  trigger:
    - platform: state
      entity_id: device_tracker.karen
      to: not_home
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode
    - service: switch.turn_off
      entity_id: switch.guest_mode_led

- alias: Guest Mode On from Keypad
  trigger:
    - platform: state
      entity_id: switch.guest_mode_led
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_mode

- alias: Guest Mode Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.guest_mode_led
      to: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode