- alias: Master Bedroom LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.master_bedroom_light_d
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom_leds_rgb
    service: light.turn_on
- alias: Master Bedroom LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.master_bedroom_light_d
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.master_bedroom_leds_rgb
    service: light.turn_off
- alias: Master Bathroom LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.master_shower_light_c
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.master_bathroom_led_rgb
    service: light.turn_on
- alias: Master Bathroom LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.master_shower_light_c
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.master_bathroom_led_rgb
    service: light.turn_off
- alias: Kitchen LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.kitchen_light_a
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.kitchen_leds_rgb
    service: light.turn_on
- alias: Kitchen LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.kitchen_light_a
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.kitchen_leds_rgb
    service: light.turn_off
- alias: Den LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.den_light_c
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.den_led_rgb
    service: light.turn_on
- alias: Den LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.den_light_c
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.den_led_rgb
    service: light.turn_off
- alias: Guest Bathroom LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.guest_bedroom_fan_c
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.guest_bathroom_led_rgb
    service: light.turn_on
- alias: Guest Bathroom LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.guest_bedroom_fan_c
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.guest_bathroom_led_rgb
    service: light.turn_off
- alias: Counter LEDs On
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.kitchen_light_b
      control: DON
  condition: []
  action:
  - data:
      entity_id: light.kitchen_counter_leds_white
    service: light.turn_on
- alias: Counter LEDs Off
  trigger:
  - platform: event
    event_type: isy994_control
    event_data:
      entity_id: switch.kitchen_light_b
      control: DOF
  condition: []
  action:
  - data:
      entity_id: light.kitchen_counter_leds_white
    service: light.turn_off