- alias: Master Shower Increase Volume
  trigger:
  - platform: state
    entity_id: light.master_shower_light_a
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/vol
      payload_template: '5,40'
- alias: Master Shower Decrease Volume
  trigger:
  - platform: state
    entity_id: light.master_shower_light_a
    to: 'off'
  action:
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/vol
      payload_template: '5,60'
- alias: Master Shower Fan Timer
  trigger:
  - platform: state
    entity_id: light.master_shower_light_1
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_shower_light_a
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/vol
      payload_template: '5,60'
  - delay: 00:10:00
  - service: switch.turn_off
    data:
      entity_id: switch.master_shower_light_a