- alias: Tablet Night
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: disarmed
    to: armed_night
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_home
    to: armed_night
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_tablet

- alias: Tablet When Home
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_night
    to: disarmed
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_night
    to: armed_home
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_away
    to: disarmed
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_tablet
      
- alias: Tablet when Away
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: armed_away
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_tablet
