- alias: Timer Lights On Main Weekday AM
  trigger:
  - platform: time
    at: '04:50:00'
  condition:
  - condition: and #Weekdays at 4:50am Not On Holiday
    conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.work_holidays
      state: 'off'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_on
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_on
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights On Main Evenings
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'   
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_on
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_on
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights On Main Weekend Holiday AM
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: disarmed
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_night
    to: armed_home    
  condition:
  - condition: and #Weekend or Holiday if up before sunrise
    conditions:
    - condition: sun
      before: sunrise
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: armed_home
    - condition: or
      conditions:
        - condition: state
          entity_id: calendar.work_holidays
          state: 'on'
        - condition: time
          weekday:
            - sat
            - sun
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_on
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_on
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_on
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights Off Main Night Away
  trigger:
  - platform: time
    at: '23:30:00'
  condition:
  - condition: state
    entity_id: alarm_control_panel.area_001
    state: armed_away
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_off
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_off
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights Off Main Mornings
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_off
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_off
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights Off Main Night Mode
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: disarmed
    to: armed_night
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_stay
    to: armed_night
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.breakfast_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.server_room_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.office_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.den_lamps
  - service: switch.turn_off
    data:
      entity_id: switch.den_table_lamp
  - service: switch.turn_off
    data:
      entity_id: switch.dining_room_lamp
  - service: light.turn_off
    data:
      entity_id: light.entry_lamp
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.timer_lights
- alias: Timer Lights On Guest
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_weekday_am
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_evenings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_wweekend_holiday_am
  condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.guest_room_lamp
- alias: Timer Lights Off Guest
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_away
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_mornings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_mode
  condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunrise
        after_offset: "+00:30:00"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.guest_room_lamp
- alias: Timer Lights On Master
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_weekday_am
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_evenings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_wweekend_holiday_am
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_home
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom_lamps
        brightness: 128
- alias: Timer Lights Off Master
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_away
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_mornings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_mode
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_home
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_bedroom_lamps
- alias: Timer Lights On Outside
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.outside_lights
  - service: switch.turn_on
    data:
      entity_id: switch.shed_porch_light
- alias: Timer Lights Off Outside
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.outside_lights
  - service: switch.turn_off
    data:
      entity_id: switch.shed_porch_light
- alias: Timer LEDs On House
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
  - platform: state
    entity_id: input_boolean.timer_lights
    to: 'on'
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_weekday_am
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_evenings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_on_main_wweekend_holiday_am
  condition:
  - condition: state
    entity_id: input_boolean.timer_lights
    state: 'on'
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_night
  action:
  - service: light.turn_on
    data:
      entity_id: light.house_leds_rgb
- alias: Timer LEDs Off House Away
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: arming
    to: armed_away
  action:
  - service: light.turn_off
    data:
      entity_id: light.house_leds_rgb
- alias: Timer LEDs Off House
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_away
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_mornings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_mode
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_leds_rgb
  - service: light.turn_off
    data:
      entity_id: light.den_led_rgb
  - service: light.turn_off
    data:
      entity_id: light.guest_bathroom_led_rgb
- alias: Timer LEDs Off Master
  trigger:
  - platform: state
    entity_id: input_boolean.timer_lights
    to: 'off'
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_away
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_mornings
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.timer_lights_off_main_night_mode
  condition:
  - condition: state
    entity_id: input_boolean.timer_lights
    state: 'off'
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: disarmed
      - condition: state
        entity_id: alarm_control_panel.area_001
        state: armed_home
  action:
  - service: light.turn_off
    data:
      entity_id: light.master_suite_leds_rgb
- alias: Master Suite Off if Sleeping
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: arming
    to: armed_night
    for: '00:45:00'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: light.master_bedroom_lamps
        state: 'on'
      - condition: state
        entity_id: light.master_suite_leds_rgb
        state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.master_bedroom_lamps
  - service: light.turn_off
    data:
      entity_id: light.master_suite_leds_rgb