light:
  - platform: mqtt
    name: "Master Bedroom LED 2 RGB"
    state_topic: "h801/mbed_2/tele/current"
    command_topic: "h801/mbed_2/command/set/rgb/power"
    brightness_state_topic: "h801/mbed_2/tele/current"
    brightness_command_topic: "h801/mbed_2/command/set/rgb/brightness"
    rgb_state_topic: "h801/mbed_2/tele/current"
    rgb_command_topic: "h801/mbed_2/command/set/rgb/color"
    state_value_template: "{{value_json['rgb_power']}}"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    qos: 0
    retain: true
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
sensor:
  #Driver Ststus Messages
  - platform: mqtt
    name: "Master Bedroom LED 2 Status"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['status']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 Version"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['espVersion']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 Uptime"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['espUptime']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 RSSI"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['signalStrength']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 IP"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 Free Heap"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['heapFree']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 Heap Fragmentation"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
  - platform: mqtt
    name: "Master Bedroom LED 2 Core Version"
    state_topic: "h801/mbed_2/tele/status"
    value_template: "{{value_json['espCore']}}" 
