#################################################################
#                                                               #
#                    Packages/data_logging                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                            Recorder                           #
#                                                               #
#################################################################

recorder:
  db_url: !secret db_url
  include:
    entities:
    - sensor.roomba_battery
    - sensor.wan_in_mbps
    - sensor.wan_out_mbps
    - sensor.wan_ping
    - sensor.attic_temperature_owfs
    - sensor.back_hvac_return_temperature_owfs
    - sensor.den_temperature_owfs
    - sensor.dining_room_temperature_owfs
    - sensor.dryer_vent_temperature_owfs
    - sensor.front_hall_temperature_owfs
    - sensor.front_hvac_return_temperature_owfs
    - sensor.garage_temperature_owfs
    - sensor.guest_bedroom_temperature_owfs
    - sensor.hvac_supply_temperature_owfs
    - sensor.master_bedroom_temperature_owfs
    - sensor.office_temperature_owfs
    - sensor.outside_temperature_owfs
    - sensor.plenum_hvac_return_temperature_owfs
    - sensor.server_room_hvac_return_temperature_owfs
    - sensor.server_room_temperature_owfs
    - sensor.shed_temperature_owfs
    - sensor.work_room_temperature_owfs
    - sensor.aquara_outside_humidity
    - sensor.aquara_outside_pressure
    - sensor.aquara_outside_temperature
    - sensor.aquara_server_closet_humidity
    - sensor.aquara_server_closet_pressure
    - sensor.aquara_server_closet_temperature
    - sensor.aquara_office_humidity
    - sensor.aquara_office_pressure
    - sensor.aquara_office_temperature
    - sensor.aquara_den_humidity
    - sensor.aquara_den_pressure
    - sensor.aquara_den_temperature
    - sensor.aquara_master_bedroom_humidity
    - sensor.aquara_master_bedroom_pressure
    - sensor.aquara_master_bedroom_temperature
    - binary_sensor.hvac_system_fan
    - binary_sensor.hvac_system_heat
    - binary_sensor.hvac_system_cool
    - binary_sensor.hvac_zone_1_fan
    - binary_sensor.hvac_zone_1_heat
    - binary_sensor.hvac_zone_1_cool
    - binary_sensor.hvac_zone_2_fan
    - binary_sensor.hvac_zone_2_heat
    - binary_sensor.hvac_zone_2_cool
    - binary_sensor.hvac_zone_3_fan
    - binary_sensor.hvac_zone_3_heat
    - binary_sensor.hvac_zone_3_cool
    - sensor.hvac_system_fan_runtime
    - sensor.hvac_system_heat_runtime
    - sensor.hvac_system_cool_runtime
    - sensor.hvac_zone_1_fan_runtime
    - sensor.hvac_zone_1_heat_runtime
    - sensor.hvac_zone_1_cool_runtime
    - sensor.hvac_zone_2_fan_runtime
    - sensor.hvac_zone_2_heat_runtime
    - sensor.hvac_zone_2_cool_runtime
    - sensor.hvac_zone_3_fan_runtime
    - sensor.hvac_zone_3_heat_runtime
    - sensor.hvac_zone_3_cool_runtime
    - sensor.hvac_system_runtime
    - sensor.hvac_zone_1_runtime
    - sensor.hvac_zone_2_runtime
    - sensor.hvac_zone_3_runtime
    - sensor.eagle_current_power
    - utility_meter.energy_daily
    - utility_meter.energy_monthly
    - utility_meter.energy_yearly

#################################################################
#                                                               #
#                            InfluxDB                           #
#                                                               #
#################################################################    

influxdb:
  host: !secret influx_host
  include:
    entities:
      - sensor.attic_temperature_owfs
      - sensor.back_hvac_return_temperature_owfs
      - sensor.den_temperature_owfs
      - sensor.dining_room_temperature_owfs
      - sensor.dryer_vent_temperature_owfs
      - sensor.front_hall_temperature_owfs
      - sensor.front_hvac_return_temperature_owfs
      - sensor.garage_temperature_owfs
      - sensor.guest_bedroom_temperature_owfs
      - sensor.hvac_supply_temperature_owfs
      - sensor.master_bedroom_temperature_owfs
      - sensor.office_temperature_owfs
      - sensor.outside_temperature_owfs
      - sensor.plenum_hvac_return_temperature_owfs
      - sensor.server_room_hvac_return_temperature_owfs
      - sensor.server_room_temperature_owfs
      - sensor.shed_temperature_owfs
      - sensor.work_room_temperature_owfs
      - sensor.aquara_outside_humidity
      - sensor.aquara_outside_pressure
      - sensor.aquara_outside_temperature
      - sensor.aquara_server_closet_humidity
      - sensor.aquara_server_closet_pressure
      - sensor.aquara_server_closet_temperature
      - sensor.aquara_office_humidity
      - sensor.aquara_office_pressure
      - sensor.aquara_office_temperature
      - sensor.aquara_den_humidity
      - sensor.aquara_den_pressure
      - sensor.aquara_den_temperature
      - sensor.aquara_master_bedroom_humidity
      - sensor.aquara_master_bedroom_pressure
      - sensor.aquara_master_bedroom_temperature
      - sensor.wan_in_mbps
      - sensor.wan_out_mbps
      - sensor.hvac_system_fan_runtime
      - sensor.hvac_system_heat_runtime
      - sensor.hvac_system_cool_runtime
      - sensor.hvac_zone_1_fan_runtime
      - sensor.hvac_zone_1_heat_runtime
      - sensor.hvac_zone_1_cool_runtime
      - sensor.hvac_zone_2_fan_runtime
      - sensor.hvac_zone_2_heat_runtime
      - sensor.hvac_zone_2_cool_runtime
      - sensor.hvac_zone_3_fan_runtime
      - sensor.hvac_zone_3_heat_runtime
      - sensor.hvac_zone_3_cool_runtime
      - sensor.hvac_system_runtime
      - sensor.hvac_zone_1_runtime
      - sensor.hvac_zone_2_runtime
      - sensor.hvac_zone_3_runtime
      - sensor.eagle_current_power
      - utility_meter.energy_daily
      - utility_meter.energy_monthly
      - utility_meter.energy_yearly
      - sensor.rain_hour
      - sensor.rain_day
      - sensor.rain_month
      - sensor.rain_year
      - sensor.rain_rate

#################################################################
#                                                               #
#                             Sensors                           #
#                                                               #
################################################################# 

sensor:

####################################################
#                                                  #
#                Sensor - EmonCMS                  #
#                                                  #
####################################################

  - platform: emoncms
    api_key: !secret emon_api
    url: https://ibnerd.net/emoncms
    scan_interval: 5
    id: 1
    unit_of_measurement: ""
    include_only_feed_id:
      - 50