#Components needed for GitHub repository and Travis CI monitoring.
sensor:
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: '/config'
  - platform: travisci
    api_key: !secret travis_access_token
    branch: dev