input_select:
  gmusic_player:
    name: Speakers
    icon: mdi:speaker-wireless
    options: ## Replace with entity_ids of your own media players
    - whole_house_audio
    - living_room_chromecast 
  gmusic_playlist:
    name: Playlists
    icon: mdi:playlist-music
    options: ## Should be empty
    - " "

switch:
  - platform: gmusic
    user: !secret gmusic_user
    password: !secret gmusic_password
    device_id: !secret gmusic_device_id
    playlist: 'gmusic_playlist'
    media_player: 'gmusic_player'
    ## Optional - Directory with RW access for gmusic_authtoken
    #token_path: '/home/hass/.local/share/gmusicapi/'


## ------------------------------------------------------------------------- ,
##  --------------   The rest of this file is optional    ----------------
## ------------------------------------------------------------------------- ,
homeassistant:
  customize:
    switch.google_music:
      friendly_name: "Google Music Switch"
      icon: mdi:power-standby
    script.gmusic_cast:
      friendly_name: Shuffle & Play
      icon: mdi:shuffle-variant

## This group may only be visable when using the "states UI"
group:
  google_music_switch:
    control: hidden
    name: Google Music
    entities:
    - switch.google_music
    - input_select.gmusic_player
    - input_select.gmusic_playlist
    - script.gmusic_cast

script:
  gmusic_cast:
    alias: Cast Google Music
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.google_music
      - service: switch.turn_on
        data:
          entity_id: switch.google_music
