sensor:
- platform: waze_travel_time
  name: "To Work"
  origin: device_tracker.shawn_n6
  destination: zone.work
  excl_string: "sam"
  region: 'US'
- platform: waze_travel_time
  name: "To Home"
  origin: device_tracker.shawn_n6
  destination: zone.home
  excl_string: "sam"
  region: 'US'