sensor:
  - platform: "mqtt"
    name: "Aquara 1 Temperature"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/aquara_env_1"
    name: "Aquara 1 Humidity"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara 1 Pressure"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara 1 Battery"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara 1 Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Aquara 2 Temperature"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    name: "Aquara 2 Humidity"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara 2 Pressure"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara 2 Battery"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara 2 Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Button 1 Press"
    state_topic: "zigbee2mqtt/button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
  - platform: "mqtt"
    name: "Button 1 Battery"
    state_topic: "zigbee2mqtt/button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Button 1 Ling Quality"
    state_topic: "zigbee2mqtt/button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Button 2 Press"
    state_topic: "zigbee2mqtt/button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
  - platform: "mqtt"
    name: "Button 2 Battery"
    state_topic: "zigbee2mqtt/button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Button 2 Ling Quality"
    state_topic: "zigbee2mqtt/button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"