- alias: Master Lamps On from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_bedroom_lamps_keypad
      to: 'on'
  condition:
    - condition: state
      entity_id: light.master_lamps
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_lamps
        brightness: 128

- alias: Master Lamps Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_bedroom_lamps_keypad
      to: 'off'
  condition:
    - condition: state
      entity_id: light.master_lamps
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.master_lamps

- alias: Master Lamps Keypad On
  trigger:
    - platform: state
      entity_id: light.master_lamps
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.master_bedroom_lamps_keypad
      state:  'off'
  action:
    - service: switch.turn_on
      entity_id: switch.master_bedroom_lamps_keypad

- alias: Master Lamps Keypad Off
  trigger:
    - platform: state
      entity_id: light.master_lamps
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.master_bedroom_lamps_keypad
      state:  'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps_keypad