- alias: Outside Lights On from Keypad
  trigger:
    - platform: state
      entity_id: switch.outside_lights_keypad
      to: 'on'
  action:
    - service: light.turn_on
      entity_id:
        - light.driveway_light
        - light.front_porch_light

- alias: Outside Lights Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.outside_lights_keypad
      to: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.driveway_light
        - light.front_porch_light

- alias: Outside Lights Keypad On
  trigger:
    - platform: state
      entity_id: 
        - light.driveway_light
        - light.front_porch_light
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.outside_lights_keypad
      state:  'off'
    - condition: state
      entity_id: light.driveway_light
      state:  'on'
    - condition: state
      entity_id: light.front_porch_light
      state:  'on'
  action:
    - service: switch.turn_on
      entity_id: switch.outside_lights_keypad

- alias: Entry Lamp Keypad Off
  trigger:
    - platform: state
      entity_id: 
        - light.driveway_light
        - light.front_porch_light
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.outside_lights_keypad
      state:  'on'
    - condition: state
      entity_id: light.driveway_light
      state:  'off'
    - condition: state
      entity_id: light.front_porch_light
      state:  'off'
  action:
    - service: switch.turn_on
      entity_id: switch.outside_lights_keypad