sensor:
  - platform: snmp
    name: 'ERL WAN In'
    host: !secret edge_os_host
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.2
    community: 'public'
    version: '2c'
    scan_interval: 10
  - platform: snmp
    name: 'ERL WAN Out'
    host: !secret edge_os_host
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.2
    community: 'public'
    version: '2c'
    scan_interval: 10
  - platform: statistics
    name: 'ERL WAN In Stats'
    entity_id: sensor.erl_wan_in
    sampling_size: 4
    max_age:
      hours: 24
  - platform: statistics
    name: 'ERL WAN Out Stats'
    entity_id: sensor.erl_wan_out
    sampling_size: 4
    max_age:
      hours: 24
  - platform: template
    sensors:
      wan_in_mbps:
        value_template: "{{ (state_attr('sensor.erl_wan_in_stats_mean','change_rate')|float*8*(state_attr('sensor.erl_wan_in_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
        unit_of_measurement: 'MBps'
        entity_id: sensor.erl_wan_in_stats_mean
      wan_out_mbps:
        value_template: "{{ (state_attr('sensor.erl_wan_out_stats_mean','change_rate')|float*8*(state_attr('sensor.erl_wan_out_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
        unit_of_measurement: 'MBps'
        entity_id: sensor.erl_wan_out_stats_mean