sensor:
  - platform: snmp
    name: 'Server UPS Battery Capacity'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.2.2.1.0
    community: 'public'
    version: '1'
    accept_errors: true
    unit_of_measurement: '%'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Remaining Runtime'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.2.2.3.0
    accept_errors: true
    unit_of_measurement: 'minutes'
    value_template: '{{((value | int) / 6000) | int}}'
  - platform: snmp
    name: 'Server UPS Battery Temperature'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.2.2.2.0
    accept_errors: true
    unit_of_measurement: "°C"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Input Voltage'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.3.2.1.0
    accept_errors: true
    unit_of_measurement: "V"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Input Frequency'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.3.2.4.0
    accept_errors: true
    unit_of_measurement: "Hz"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Output Voltage'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.4.2.1.0
    accept_errors: true
    unit_of_measurement: "V"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Output Frequency'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.4.2.2.0
    accept_errors: true
    unit_of_measurement: "Hz"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Output Current'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.8.1.0
    accept_errors: true
    unit_of_measurement: "A"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Output Load'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.4.2.3.0
    accept_errors: true
    unit_of_measurement: "%"
    community: 'public'
    version: '1'
    scan_interval: 10
  - platform: snmp
    name: 'Server UPS Battery Status'
    host: !secret server_ups_host
    baseoid: .1.3.6.1.4.1.318.1.1.1.2.2.4.0
    accept_errors: true
    community: 'public'
    version: '1'
    scan_interval: 10